#!/bin/bash

# Author: Reshma Shriyan
# Date Created: 05/07/2021
# Date Modified: 05/07/2021

# Description: For calculations

# Usage:
# arithmatic_script


x=5
y=8
echo $((x+y))
echo $((x-y))
echo $((x/y))
echo $((x*y))

#Square or x raised to the power 2
echo $((x**2))

#Calcuate remainder
echo $((x%5))
echo $((x%y))

#It will throw error for echo $((2.5+1) -- Arithemetic expansions  doesnt take decimal 
#Output for echo $$(5/2) will  be 2, as it  doesnt provide decimal output either

#bc command which stands for basic calculator can be used to work with decimal number in bash


