#!/bin/bash

# Author: Reshma Shriyan
# Date Created: 05/06/2021
# Date Modified: 05/06/2021

# Description: This script will backup all the files in home directory and save them all in a .tar archive

# Usage:
# backup_script

tar -cvf ~/bash_course/my_backup_"$(date +%d-%m-%Y_%H-%M-%S)".tar ~/* 2 > /dev/null

exit 0

# End of script
